In [1]:
# import pandas and numpy
import pandas as pd
import numpy as np

In [2]:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

In [3]:
# import json
import json
from pandas.io.json import json_normalize

In [4]:
# load the json file as string
data = json.load((open('data/world_bank_projects.json')))

In [5]:
# normalize extracting the fields needed for the assignment
df = json_normalize(data, 'mjtheme_namecode', ['countryshortname', ['_id', '$oid']] )

In [6]:
# check to see if the result looks reasonable
df.head()

,code,name,countryshortname,_id.$oid
0,8,Human development,Ethiopia,52b213b38594d8a2be17c780
1,11,,Ethiopia,52b213b38594d8a2be17c780
2,1,Economic management,Tunisia,52b213b38594d8a2be17c781
3,6,Social protection and risk management,Tunisia,52b213b38594d8a2be17c781
4,5,Trade and integration,Tuvalu,52b213b38594d8a2be17c782

In [7]:
# get the list of top 10 countries that have the most projects
df.countryshortname.value_counts()

Indonesia                           56
India                               51
Vietnam                             43
Brazil                              41
Bangladesh                          41
China                               40
Africa                              39
Yemen, Republic of                  34
Morocco                             32
Mozambique                          31
Nepal                               29
Tanzania                            28
Burkina Faso                        26
Tajikistan                          25
Pakistan                            25
Lao People's Democratic Republic    24
Afghanistan                         23
Kyrgyz Republic                     22
Nigeria                             22
Armenia                             22
Niger                               21
Haiti                               19
Peru                                19
Congo, Democratic Republic of       18
Jordan                              18
Kenya                               18
West Bank and Gaza                  17
Nicaragua                           17
Uzbekistan                          16
Bhutan                              16
                                    ..
South Asia                           5
Kosovo                               5
Marshall Islands                     5
Timor-Leste                          5
Sierra Leone                         5
Europe and Central Asia              5
Antigua and Barbuda                  4
Chile                                4
Gambia, The                          4
Ecuador                              4
Egypt, Arab Republic of              4
Jamaica                              4
Tuvalu                               4
Tonga                                4
Sri Lanka                            4
Cape Verde                           4
Namibia                              4
Thailand                             3
Zimbabwe                             3
East Asia and Pacific                3
Serbia                               3
Bosnia and Herzegovina               3
Congo, Republic of                   2
Belarus                              2
Chad                                 2
Angola                               2
Costa Rica                           2
Central African Republic             2
Romania                              2
Kiribati                             2
Name: countryshortname, dtype: int64

In [8]:
# get the top 10 major project themes.  
df.name.value_counts()

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Economic management                              33
Rule of law                                      12
Name: name, dtype: int64

In [9]:
# Note that there is missing data from the 'name' column invalidating the previous result
# sort the dataframe by code so we can find and fill the empty spots in 'name'
df_sorted = df.sort(['code','name'])

In [10]:
#  check to see if we need to do a back or forward fill
df_sorted[df_sorted.code == '1']

,code,name,countryshortname,_id.$oid
212,1,,Liberia,52b213b38594d8a2be17c7ce
363,1,,Cote d'Ivoire,52b213b38594d8a2be17c802
1024,1,,Tanzania,52b213b38594d8a2be17c8da
1114,1,,Honduras,52b213b38594d8a2be17c8f7
1437,1,,Guatemala,52b213b38594d8a2be17c95f
2,1,Economic management,Tunisia,52b213b38594d8a2be17c781
88,1,Economic management,Seychelles,52b213b38594d8a2be17c7a1
175,1,Economic management,Afghanistan,52b213b38594d8a2be17c7c0
204,1,Economic management,Kyrgyz Republic,52b213b38594d8a2be17c7cb
205,1,Economic management,Kyrgyz Republic,52b213b38594d8a2be17c7cb
220,1,Economic management,Tunisia,52b213b38594d8a2be17c7d1
222,1,Economic management,Jordan,52b213b38594d8a2be17c7d2
223,1,Economic management,Mozambique,52b213b38594d8a2be17c7d3
249,1,Economic management,Armenia,52b213b38594d8a2be17c7de
357,1,Economic management,Poland,52b213b38594d8a2be17c801
453,1,Economic management,Lesotho,52b213b38594d8a2be17c81e
454,1,Economic management,Sao Tome and Principe,52b213b38594d8a2be17c81f
458,1,Economic management,Sao Tome and Principe,52b213b38594d8a2be17c81f
497,1,Economic management,Malawi,52b213b38594d8a2be17c82d
647,1,Economic management,Lao People's Democratic Republic,52b213b38594d8a2be17c85c
648,1,Economic management,Lao People's Democratic Republic,52b213b38594d8a2be17c85c
784,1,Economic management,Tanzania,52b213b38594d8a2be17c889
803,1,Economic management,Panama,52b213b38594d8a2be17c88e
841,1,Economic management,Vietnam,52b213b38594d8a2be17c89a
900,1,Economic management,"Yemen, Republic of",52b213b38594d8a2be17c8ad
1010,1,Economic management,Myanmar,52b213b38594d8a2be17c8d4
1045,1,Economic management,"Macedonia, former Yugoslav Republic of",52b213b38594d8a2be17c8e0
1056,1,Economic management,Azerbaijan,52b213b38594d8a2be17c8e5
1057,1,Economic management,Azerbaijan,52b213b38594d8a2be17c8e5
1078,1,Economic management,Ukraine,52b213b38594d8a2be17c8eb
1206,1,Economic management,Pacific Islands,52b213b38594d8a2be17c911
1212,1,Economic management,Kenya,52b213b38594d8a2be17c913
1218,1,Economic management,Tonga,52b213b38594d8a2be17c915
1229,1,Economic management,Colombia,52b213b38594d8a2be17c919
1230,1,Economic management,Colombia,52b213b38594d8a2be17c919
1235,1,Economic management,Uruguay,52b213b38594d8a2be17c91a
1257,1,Economic management,Maldives,52b213b38594d8a2be17c923
1260,1,Economic management,Jordan,52b213b38594d8a2be17c924

In [11]:
# replace the "empty" spots, ones with u'', with Nan, then back fill using fillna
df_sorted.replace(u'', np.nan).fillna(method='bfill')

,code,name,countryshortname,_id.$oid
212,1,Economic management,Liberia,52b213b38594d8a2be17c7ce
363,1,Economic management,Cote d'Ivoire,52b213b38594d8a2be17c802
1024,1,Economic management,Tanzania,52b213b38594d8a2be17c8da
1114,1,Economic management,Honduras,52b213b38594d8a2be17c8f7
1437,1,Economic management,Guatemala,52b213b38594d8a2be17c95f
2,1,Economic management,Tunisia,52b213b38594d8a2be17c781
88,1,Economic management,Seychelles,52b213b38594d8a2be17c7a1
175,1,Economic management,Afghanistan,52b213b38594d8a2be17c7c0
204,1,Economic management,Kyrgyz Republic,52b213b38594d8a2be17c7cb
205,1,Economic management,Kyrgyz Republic,52b213b38594d8a2be17c7cb
220,1,Economic management,Tunisia,52b213b38594d8a2be17c7d1
222,1,Economic management,Jordan,52b213b38594d8a2be17c7d2
223,1,Economic management,Mozambique,52b213b38594d8a2be17c7d3
249,1,Economic management,Armenia,52b213b38594d8a2be17c7de
357,1,Economic management,Poland,52b213b38594d8a2be17c801
453,1,Economic management,Lesotho,52b213b38594d8a2be17c81e
454,1,Economic management,Sao Tome and Principe,52b213b38594d8a2be17c81f
458,1,Economic management,Sao Tome and Principe,52b213b38594d8a2be17c81f
497,1,Economic management,Malawi,52b213b38594d8a2be17c82d
647,1,Economic management,Lao People's Democratic Republic,52b213b38594d8a2be17c85c
648,1,Economic management,Lao People's Democratic Republic,52b213b38594d8a2be17c85c
784,1,Economic management,Tanzania,52b213b38594d8a2be17c889
803,1,Economic management,Panama,52b213b38594d8a2be17c88e
841,1,Economic management,Vietnam,52b213b38594d8a2be17c89a
900,1,Economic management,"Yemen, Republic of",52b213b38594d8a2be17c8ad
1010,1,Economic management,Myanmar,52b213b38594d8a2be17c8d4
1045,1,Economic management,"Macedonia, former Yugoslav Republic of",52b213b38594d8a2be17c8e0
1056,1,Economic management,Azerbaijan,52b213b38594d8a2be17c8e5
1057,1,Economic management,Azerbaijan,52b213b38594d8a2be17c8e5
1078,1,Economic management,Ukraine,52b213b38594d8a2be17c8eb
...,...,...,...,...
597,9,Urban development,"Congo, Democratic Republic of",52b213b38594d8a2be17c84d
598,9,Urban development,"Congo, Democratic Republic of",52b213b38594d8a2be17c84d
650,9,Urban development,Vietnam,52b213b38594d8a2be17c85d
669,9,Urban development,Mozambique,52b213b38594d8a2be17c865
732,9,Urban development,China,52b213b38594d8a2be17c87a
737,9,Urban development,Uganda,52b213b38594d8a2be17c87c
738,9,Urban development,Uganda,52b213b38594d8a2be17c87c
739,9,Urban development,South Sudan,52b213b38594d8a2be17c87d
742,9,Urban development,South Sudan,52b213b38594d8a2be17c87d
822,9,Urban development,China,52b213b38594d8a2be17c893
917,9,Urban development,Thailand,52b213b38594d8a2be17c8b3
930,9,Urban development,Rwanda,52b213b38594d8a2be17c8b9
940,9,Urban development,Morocco,52b213b38594d8a2be17c8bc
962,9,Urban development,Middle East and North Africa,52b213b38594d8a2be17c8c2
1095,9,Urban development,Honduras,52b213b38594d8a2be17c8f2
1102,9,Urban development,Colombia,52b213b38594d8a2be17c8f4
1103,9,Urban development,Colombia,52b213b38594d8a2be17c8f4
1104,9,Urban development,Colombia,52b213b38594d8a2be17c8f4
1166,9,Urban development,West Bank and Gaza,52b213b38594d8a2be17c905
1290,9,Urban development,Tanzania,52b213b38594d8a2be17c930
1303,9,Urban development,Bolivia,52b213b38594d8a2be17c933
1318,9,Urban development,Nepal,52b213b38594d8a2be17c938
1342,9,Urban development,Africa,52b213b38594d8a2be17c941
1347,9,Urban development,Bangladesh,52b213b38594d8a2be17c942
1425,9,Urban development,Pakistan,52b213b38594d8a2be17c95a
1426,9,Urban development,Pakistan,52b213b38594d8a2be17c95a
1428,9,Urban development,Indonesia,52b213b38594d8a2be17c95b
1470,9,Urban development,Papua New Guinea,52b213b38594d8a2be17c969
1473,9,Urban development,Papua New Guinea,52b213b38594d8a2be17c969
1495,9,Urban development,Kenya,52b213b38594d8a2be17c973

In [12]:
# redo the count of top 10 projects to update the numbers after filling in missing data
df_sorted.replace(u'', np.nan).fillna(method='bfill').name.value_counts()

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
Rule of law                                      15
Name: name, dtype: int64